import type { PluItem } from './types';

const rawData = `PLU,Korean,English,French,Season
1000,가지,Eggplant,Aubergine,"Jul-Sep"
1023,감자,Potato,Pomme De Terre,"Year-round"
1023,감자(5Lbs),Potato (5Lbs),Pomme De Terre (5 Livres),"Year-round"
1024,화이트 감자,White Potato,Pomme De Terre Blanche,"Year-round"
1028,블랙 감자,Black Potato,Pomme De Terre Noire,"Year-round"
1030,화이트 베이비 감자,White Baby Potato,Pomme De Terre Grelot Blanche,"Year-round"
1030,화이트 베이비 감자(Pack),White Baby Potato (Pack),Pomme De Terre Grelot Blanche (Paquet),"Year-round"
1035,러셋 감자,Russet Potato,Pomme De Terre Russet,"Year-round"
1048,고구마,Sweet Potato,Patate Douce,"Sep-Nov"
1053,퍼플 고구마,Purple Sweet Potato,Patate Douce Violette,"Sep-Nov"
1087,당근,Carrot,Carotte,"Year-round"
1087,당근 (내부),Carrot (Int),Carotte (Int),"Year-round"
1093,베이비 당근,Baby Carrot ,Bébé Carotte,"Year-round"
1107,우엉,Gobo,Gobo,"Mar-May"
1114,연근,Lotus Root,Racine De Lotus,"Sep-Nov"
1119,베이비 타로,Small Taro,Petit Taro,"Year-round"
1125,무우,Radish,Radis,"Oct-Dec"
1128,다이콘 무우,Daikon Radish,Radis Daikon,"Oct-Dec"
1172,마늘(3Pcs),Garlic  (3Pcs),Ail (3Pcs),"Year-round"
1178,마늘쫑,Garlic Stem,Tige D’Ail,"Apr-Jun"
1182,깐마늘,Peeled Garlic,Ail Pelé,"Year-round"
1186,생강,Ginger,Gingembre,"Year-round"
1187,갈랑가,Galanga,Galanga,"Year-round"
1192,양파,Onion,Oignon,"Year-round"
1192,양파(2Lbs),Onion (2Lbs),Oignon (2Lbs),"Year-round"
1192,양파(10Lbs),Onion (10Lbs),Oignon (10Lbs),"Year-round"
1194,화이트 양파,White Onion,Oignon Blanc,"Year-round"
1196,레드 양파,Red Onion,Oignon Rouge,"Year-round"
1216,대파,Welsh Onion,Ciboule,"Year-round"
1217,쪽파,Small Green Onion,Petit Oignon Vert,"Year-round"
1219,릭,Leek,Poireau,"Sep-Apr"
1227,한국 고추,Korean Pepper,Poivre Coréen,"Jul-Sep"
1227,한국 고추(Pack),Korean Pepper (Pack),Poivre Coréen (Paquet),"Jul-Sep"
1228,한국 청양 고추,Korean Hot Pepper,Piment Fort Coréen,"Jul-Sep"
1228,한국 청양 고추(Pack),Korean Hot Pepper (Pack),Piment Fort Coréen (Paquet),"Jul-Sep"
1229,한국 레드 고추,Korean Red Pepper,Poivron Rouge Coréen,"Jul-Sep"
1231,꽈리 고추,Sweet Pepper,Poivron,"Jul-Sep"
1231,꽈리 고추(Pack),Sweet Pepper (Pack),Poivron Doux (Paquet),"Jul-Sep"
1240,피망 믹스 팩 #1,Mixed Bell Pepper #1,Poivron Mélangé #1,"Year-round"
1242,그린 피망,Green Bell Pepper,Poivron Vert,"Year-round"
1243,레드 피망,Red Bell Pepper,Poivron Rouge,"Year-round"
1244,오렌지 피망,Orange Bell Pepper,Poivron Orange,"Year-round"
1245,옐로우 피망,Yellow Bell Pepper,Poivron Jaune,"Year-round"
1254,타이 그린 페퍼,Thai Green Pepper,Poivron Vert Thaï,"Year-round"
1255,타이 레드 페퍼,Thai Red Pepper,Poivron Rouge Thaïlandais,"Year-round"
1259,하바네로 레드 페퍼,Habanero Red Pepper,Habanero Poivron Rouge,"Year-round"
1263,시시토 페퍼,Shishito Pepper ,Piment Shishito,"Year-round"
1269,롱 그린 핫 페퍼,Long Green Hot Pepper,Piment Vert Long,"Year-round"
1297,미니 피망,Mini Bell Pepper,Mini Poivron,"Year-round"
1298,핑거 고추,Finger Pepper,Poivron Doigt,"Jul-Sep"
1307,킹 느타리 버섯,King Oyster Mushroom,Pleurote Royal,"Year-round"
91307,유기농 킹 느타리 버섯,Organic King Oyster Mushroom ,Pleurote Royal (Bio),"Year-round"
1308,베이비 느타리 버섯,Baby Oyster Mushroom,Bébé Pleurote,"Year-round"
1309,느타리 버섯 (내부),Oyster Mushroom (Int),Pleurote (Int),"Year-round"
1311,표고 버섯,Shiitake Mushroom,Champignon Shiitake,"Year-round"
1315,해물 버섯,Seafood Mushroom,Champignons De La Mer,"Year-round"
1316,팽이 버섯,Enoki Mushroom,Champignon Enoki,"Year-round"
91316,유기농 팽이 버섯,Organic Enoki Mushroom ,Champignon Enoki Bio,"Year-round"
1321,포타 벨라 버섯,Portobella Mushroom,Champignon Portobella,"Year-round"
1327,화이트 양송이 버섯,White Mushroom,Champignon Blanc,"Year-round"
1327,화이트 양송이 버섯(Bulk),White Mushroom (Bulk),Champignon Blanc (En Vrac),"Year-round"
1328,브라운 양송이 버섯,Brown Mushroom,Champignon Brun,"Year-round"
1336,화이트 시메지 버섯,White Shimeji Mushroom,Champignon Shimeji Blanc,"Year-round"
1337,브라운 시메지 버섯,Brown Shimeji Mushroom,Champignon Shimeji Brun,"Year-round"
1340,모듬 버섯,Assorted Mushroom,Champignons Assortis,"Year-round"
91340,유기농 모듬 버섯,Organic Assorted Mushroom ,Assortiment De Champignons (Bio),"Year-round"
1341,블랙 느타리 버섯,Black Oyster Mushroom,Pleurote Noir,"Year-round"
91341,유기농 블랙 느타리 버섯,Organic Black Oyster Mushroom ,Pleurote Noir Bio,"Year-round"
1342,화이트 양송이 버섯 (점보),White Mushroom (Jumbo),Champignon Blanc (Jumbo),"Year-round"
1343,슬라이스 버섯,Sliced Mushroom,Champignons Tranchés,"Year-round"
91344,유기농 사자 갈기 버섯,Organic Lion'S Mane Mushroom ,Champignon Crinière De Lion (Bio),"Year-round"
1351,워터크래스,Watercress,Cresson De Fontaine,"Apr-Oct"
1361,고구마순 (내부),Sweet Potato Stem  (Int),Tige De Patate Douce,"Jul-Aug"
1377,곰취나물(Pack),Aster Greens (Pack),Feuilles D’Aster (Paquet),"Apr-May"
1379,아욱(Pack),Cluster Mallow (Pack),Mauve À Grappes (Paquet),"Sep-Oct"
1399,쑥갓,Crown Daisy,Marguerite Couronne,"Apr-Jun"
1405,시금치,Spinach,Épinard,"Mar-May, Sep-Nov"
91405,유기농 시금치,Organic Spinach ,Épinards Biologiques,"Mar-May, Sep-Nov"
1405,시금치 (내부),Spinach (Int),Épinards (Int),"Mar-May, Sep-Nov"
1409,베이비 시금치,Baby Spinach,Bébés Épinards,"Year-round"
1413,부추,Chive,Ciboulette,"Apr-Oct"
1414,한국 부추(Pack),Korean Chive (Pack),Ciboulette Coréenne (Paquet),"Apr-Oct"
1445,그린 케일,Green Kale,Chou Frisé Vert,"Year-round"
1446,레드 케일,Red Kale,Chou Frisé Rouge,"Year-round"
1452,배추,Napa,Napa,"Oct-Dec"
1461,박초이,Bok Choy,Bok Choy,"Year-round"
1463,박초이 팁,Bok Choy Tip,Pointe De Bok Choy,"Year-round"
1465,청경채,Shanghai Bok Choy,Shanghai Bok Choy,"Year-round"
1466,청경채 팁,Shanghai Bok Choy Tip,Pointe De Bok Choy De Shanghai,"Year-round"
1479,유초이,Yu Choy,Yu Choy,"Year-round"
1497,양배추,Cabbage,Chou,"Year-round"
1498,레드 양배추,Red Cabbage,Chou Rouge,"Year-round"
1500,사보이 양배추,Savoy Cabbage,Chou De Savoie,"Year-round"
1503,납작 양배추,Flat Cabbage,Chou Plat,"Year-round"
1513,그린 상추,Green Leaf Lettuce,Laitue Frisée Verte,"Year-round"
1514,레드 상추,Red Leaf Lettuce,Laitue Frisée Rouge,"Year-round"
1515,양상추,Iceberg Lettuce,Laitue Iceberg,"Year-round"
91515,유기농 양상추,Organic Iceberg Lettuce ,Laitue Iceberg Biologique,"Year-round"
1516,로메인 상추,Romaine Lettuce,Laitue Romaine,"Year-round"
1519,보스턴 상추,Boston Lettuce,Laitue Boston,"Year-round"
1523,크리스피 상추,Crisp Lettuce,Laitue Croquante,"Year-round"
1528,잎 깻잎,Sesame Leaf,Feuille De Sésame,"Jun-Aug"
1532,추부 깻잎,Chubu Sesame Leaf,Feuille De Sésame Chubu,"Jun-Aug"
1550,코리안더,Coriander,Coriandre,"Year-round"
1553,딜(Pack),Dill (Pack),Aneth (Paquet),"Year-round"
1554,오레가노(Pack),Oregano (Pack),Origan (Paquet),"Year-round"
1555,민트,Mint,Menthe,"Year-round"
1558,로즈마리,Rosemary,Romarin,"Year-round"
1558,로즈마리(Pack),Rosemary (Pack),Romarin,"Year-round"
1566,타미(Pack),Thyme (Pack),Thym (Paquet),"Year-round"
1571,레몬그라스,Lemongrass,Citronnelle,"Year-round"
1571,레몬그라스(Pack),Lemongrass (Pack),Citronnelle (Paquet),"Year-round"
1615,라임 잎,Lime Leaf,Feuille De Tilleul,"Year-round"
1634,아스파라거스,Asparagus,Asperge,"Apr-Jun"
1656,샐러리,Celery,Céleri,"Year-round"
1668,컬리 파슬리,Curly Parsley,Persil Frisé,"Year-round"
1672,바질,Basil,Basilic,"Year-round"
1672,바질(Pack),Basil (Pack),Basilic (Paquet),"Year-round"
1674,타이 바질,Thai Basil,Basilic Thaï,"Year-round"
1688,그린 콩,Green Bean ,Haricot,"Jun-Sep"
1714,스노우 피,Snow Pea,Pois Mange-Tout,"Apr-Jun"
1715,스냅 피,Snap Pea ,Pois Mange-Tout,"Apr-Jun"
1720,숙주,Mung Bean Sprout,Germe De Haricot Mungo,"Year-round"
1730,그린 호박,Green Squash,Courge Verte,"Jun-Aug"
1731,그레이 호박,Grey Squash,Courge Grise,"Jun-Aug"
1732,옐로우 호박,Yellow Squash,Courge Jaune,"Jun-Aug"
1739,버터넛 호박,Butternut Squash,Courge Musquée,"Sep-Nov"
1753,단호박,Kabocha Squash,Courge Kabocha,"Sep-Nov"
1768,브로콜리,Broccoli,Brocoli,"Year-round"
1769,중국 브로콜리,Chinese Broccoli,Brocoli Chinois,"Year-round"
1770,중국 브로콜리 팁,Chinese Broccoli Tip,Astuce De Brocoli Chinois,"Year-round"
1779,컬리플라워,Cauliflower,Chou-Fleur,"Year-round"
1793,미국 오이,English Cucumber,Concombre Anglais,"Year-round"
1795,피클 오이,Pickle Cucumber,Cornichon Concombre,"Year-round"
1804,미니 오이,Mini Cucumber,Mini Concombre,"Year-round"
1833,토마토,Tomato,Tomate,"Jun-Sep"
1834,로마 토마토,Roma Tomato,Tomate Roma,"Jun-Sep"
1837,줄기 토마토,Cluster Tomato,Tomate En Grappe,"Jun-Sep"
1843,헤일롬 토마토,Heirloom Tomato,Tomate Ancienne,"Jul-Sep"
1844,체리 토마토,Cherry Tomato,Tomate Cerise,"Jun-Sep"
91844,유기농 체리 토마토,Organic Cherry Tomato ,Tomate Cerise (Bio),"Jun-Sep"
1858,체리 토마토 믹스,Assorted Cherry Tomato,Assortiment De Tomates Cerises,"Jun-Sep"
1874,옥수수,Sweet Corn,Maïs,"Jul-Aug"
1878,베이비 옥수수,Baby Corn,Maïs Miniature,"Jul-Aug"
2000,단감,Persimmon ,Kaki,"Oct-Nov"
2017,망고,Mango,Mangue,"Year-round"
2018,아탈포 망고,Ataulfo Mango,Ataulfo Mangue,"Mar-Jul"
2020,켄트 망고,Kent Mango ,Mangue Du Kent,"Jun-Sep"
2021,타미 망고,Tommy Mango ,Tommy Mango,"Mar-Jul"
2028,헤이든 망고,Haden Mango,Mangue Haden,"Mar-May"
2030,케이트 망고,Keitt Mango,Keitt Mangue,"Aug-Sep"
2033,넥타린 망고,Nectarine Mango,Nectarine Mangue,"Year-round"
2034,말리카 망고,Mallika Mango,Mallika Mangue,"Jun-Jul"
2044,한국 참외,Korean Melon ,Melon Coréen,"Jun-Aug"
2052,수박,Watermelon ,Pastèque,"Jun-Aug"
2053,씨 없는 수박,Seedless Watermelon,Pastèque Sans Pépins,"Jun-Aug"
2054,미니 수박,Mini Watermelon,Mini Pastèque,"Jun-Aug"
2068,멜론,Melon,Melon,"Jun-Aug"
2072,카나리 멜론,Canary Melon ,Melon Des Canaries,"Jun-Aug"
2099,칸탈리나 멜론,Cantaline Melon,Cantaline Melon,"Jun-Aug"
2111,허니듀,Honeydew,Miellat,"Jun-Aug"
2112,골든 허니듀,Golden Honeydew,Mhoneydat Doré,"Jun-Aug"
2121,켄탈롭,Cantaloupe,Cantaloup,"Jun-Aug"
2130,복숭아,Peach,Pêche,"Jul-Aug"
2131,백도 복숭아,White Peach,Pêche Blanche,"Jul-Aug"
2132,황도 복숭아,Yellow Peach,Pêche Jaune,"Jul-Aug"
2133,화이트 도넛 복숭아,White Donut Peach,Beignet Blanc Pêche,"Jul-Aug"
2133,화이트 도넛 복숭아(Pack),White Donut Peach (Pack),Beignet Blanc Pêche,"Jul-Aug"
2147,천도 복숭아,Nectarine,Nectarine,"Jul-Aug"
2148,백 천도 복숭아,White Nectarine,Nectarine Blanche,"Jul-Aug"
2149,황도 천도 복숭아,Yellow Nectarine,Nectarine Jaune,"Jul-Aug"
2160,한국 신고배,Korean Singo  Pear,Poire Singo Coréenne,"Sep-Nov"
2160,한국 신고배(3Pcs),Korean Singo  Pear (3Pcs),Poire Singo Coréenne (3Pcs),"Sep-Nov"
2169,아시안 배,Asian Pear,Poire Asiatique,"Sep-Nov"
2179,포렐 배,Forelle Pear,Poire Forelle,"Oct-Jan"
2184,버틀렛 배,Bartlett Pear,Poire Bartlett,"Aug-Oct"
2196,로차 배,Rocha Pear,Poire Rocha,"Sep-Oct"
2207,후지 사과,Fuji Apple,Fuji Pomme,"Sep-May"
2208,갈라 사과,Gala Apple,Gala Pomme,"Aug-Apr"
2211,그래니 스미스 사과,Granny Smith Apple,Pomme Granny Smith,"Sep-Jun"
2212,허니크리스피 사과,Honeycrisp Apple,Pomme Honeycrisp,"Sep-Feb"
2217,레드 델리셔스 사과,Red Delicious Apple,Pomme Rouge Délicieuse,"Sep-May"
2225,핑크 레이디 사과,Pink Lady Apple,Pomme Dame Rose,"Oct-Jun"
2237,앰버로사 사과,Ambrosia Apple,Pomme Ambroisie,"Sep-Mar"
2287,레드 자두,Red Plum,Prune Rouge,"Jun-Sep"
2288,옐로우 자두,Yellow Plum,Prune Jaune,"Jun-Sep"
2289,블랙 자두,Black Plum,Prune Noire,"Jun-Sep"
2290,그린 자두,Green Plum,Prune Verte,"Jun-Sep"
2321,살구,Apricot,Abricot,"Jun-Jul"
2323,레드 살구 ,Red Apricot,Abricot Rouge,"Jun-Jul"
2330,아프리움,Apriums,Apriums,"Jun-Jul"
2376,레드 포도,Red Grape,Raisin Rouge,"Year-round"
2377,그린 포도,Green Grape,Raisin Vert,"Year-round"
2378,블랙 포도,Black Grape,Raisin Noir,"Year-round"
2379,레드 씨없는 포도,Red Seedless Grape,Raisin Rouge Sans Pépins,"Year-round"
2380,그린 씨없는 포도,Green Seedless Grape,Raisin Vert Sans Pépins,"Year-round"
2381,블랙 씨없는 포도,Black Seedless Grape,Raisin Noir Sans Pépins,"Year-round"
2392,솜사탕 포도(Pack),Cotton Candy Grape (Pack),Barbe À Papa Raisin (Paquet),"Aug-Sep"
2392,솜사탕 포도,Cotton Candy Grape,Barbe À Papa Raisin,"Aug-Sep"
2402,레드 캔디 포도(Pack),Red Candy Grape (Pack),Raisin Candy Rouge (Paquet),"Aug-Sep"
2423,딸기,Strawberry,Fraise,"May-Jul"
92423,유기농 딸기,Organic Strawberry ,Fraise (Bio),"May-Jul"
2424,블루베리,Blueberry,Myrtille,"Jun-Aug"
92424,유기농 블루베리,Organic Blueberry ,Myrtille (Bio),"Jun-Aug"
2425,블랙베리,Blackberry,Mûre,"Jun-Aug"
92425,유기농 블랙베리,Organic Blackberry ,Mûre (Bio),"Jun-Aug"
2426,라스베리,Raspberry,Framboise,"Jun-Aug"
92426,유기농 라스베리,Organic Raspberry ,Framboise Biologique,"Jun-Aug"
2449,만다린,Mandarin,Mandarin,"Nov-Jan"
92449,유기농 만다린(2Lbs),Organic Mandarin (2Lbs),Mandarine (Bio) (2Lbs),"Nov-Jan"
2457,오리 만다린,Orri Mandarin ,Orri Mandarine,"Jan-Apr"
2458,스윗 만다린,Sweet Mandarin ,Mandarine Douce,"Nov-Jan"
2485,클레멘타인,Clementine,Clémentine,"Nov-Jan"
2499,만다린(2Lbs),Mandarin(2Lbs),Mandarin(2Lbs),"Nov-Jan"
2505,오렌지,Orange,Orange,"Dec-Mar"
2506,네이블 오렌지,Navel Orange,Orange Nombril,"Dec-Mar"
2512,카라카라 오렌지,Caracara Orange,Caracara Orange,"Dec-Mar"
2517,골드너겟 오렌지,Gold Nugget Orange,Pépite D’Or Orange,"Mar-May"
2551,금귤,Kumquat,Kumquat,"Dec-Feb"
2587,레몬,Lemon,Citron,"Year-round"
2593,라임,Lime,Chaux,"Year-round"
2603,모과,Quince,Coing,"Sep-Oct"
2608,레드 체리(Pack),Red Cherry (Pack),Cerise Rouge (Paquet),"Jun-Jul"
2608,레드 체리,Red Cherry,Cerise Rouge,"Jun-Jul"
2617,키위,Kiwi,Kiwi,"Oct-Feb"
2618,그린 키위,Green Kiwi,Kiwi Vert,"Oct-Feb"
2618,그린 키위(Pack),Green Kiwi (Pack),Kiwi Vert (Paquet),"Oct-Feb"
2619,골드 키위,Gold Kiwi,Kiwi Doré,"Oct-Feb"
2620,레드 키위,Red Kiwi,Kiwi Rouge,"Oct-Nov"
2626,리치,Lychee,Litchi,"Jun-Jul"
2627,롱안,Longan,Longane,"Jul-Aug"
2628,람부탄,Rambutan,Ramboutan,"Jul-Sep"
2632,패션 후루츠,Passion Fruit,Passion Fruit,"Year-round"
2634,스타 후르츠,Star Fruit,Carambole,"Year-round"
2664,구아바,Guava,Goyave,"Year-round"
2674,코코넛,Coconut,Noix De Coco,"Year-round"
2686,파파야,Papaya,Papaye,"Year-round"
2705,파인애플,Pineapple,Ananas,"Year-round"
2721,드래곤 후르츠,Dragonfruit,Fruit Du Dragon,"Year-round"
2722,레드 드래곤 후르츠,Red Dragonfruit,Fruit Du Dragon Rouge,"Year-round"
2723,옐로우 드래곤 후르츠,Yellow Dragon Fruit,Fruit Du Dragon Jaune,"Year-round"
2728,바나나,Banana,Banane,"Year-round"
92728,유기농 바나나,Organic Banana ,Banane (Bio),"Year-round"
92731,유기농 베이비 바나나,Organic Baby Banana ,Bébé Banane Biologique,"Year-round"
2769,석류,Pomegranate,Grenade,"Sep-Nov"
2775,무화과,Figs,Figue,"Aug-Oct"
2781,말린 무화과,Dried Figs,Figues Séchées,"Year-round"
2793,말린 대추,Dried Jujube,Jujube Séché,"Year-round"
2796,아보카도,Avocado,Avocat,"Year-round"
2796,아보카도(2Lbs),Avocado (2Lbs),Avocat (2Lbs),"Year-round"
2879,밤,Chestnut,Châtaigne,"Sep-Oct"
96008,유기농 레몬 즙 (소),Organic Lemon Juice (Small) ,Jus De Citron (Bio) (Petit),"Year-round"
6008,레몬 즙 (소),Lemon Juice (Small),Jus De Citron (Petit),"Year-round"
96009,유기농 라임 즙 (소),Organic Lime Juice (Small) ,Jus De Citron Vert (Bio) (Petit),"Year-round"
6009,라임 즙 (소),Lime Juice (Small),Jus De Citron Vert (Petit),"Year-round"
`;

const cleanedData = rawData.trim().replace(/^\uFEFF/, '');
const lines = cleanedData.split('\n');

export const pluData: PluItem[] = lines
  .slice(1) // Skip header row
  .map(line => {
    // This is a simple CSV parser, it won't handle commas within quotes.
    // Our data seems simple enough for this to work.
    const values = line.split(',');
    if (values.length >= 5) {
      return {
        plu: values[0]?.trim() || '',
        korean: values[1]?.trim() || '',
        english: values[2]?.trim() || '',
        french: values.slice(3, values.length - 1).join(',').trim() || '',
        season: values[values.length - 1]?.trim().replace(/"/g, '') || 'N/A',
      };
    }
    return null;
  })
  .filter((item): item is PluItem => item !== null && item.plu !== '')
  .filter(item => !item.korean.includes('(내부)'));
